# From omerxx/dotfiles + essentials for Nerd Font & theme
font-family = JetBrainsMono Nerd Font Mono
font-size = 12
font-feature = calt
font-feature = liga
theme = Catppuccin Mocha
background-opacity = 0.8
background-blur-radius = 20
mouse-hide-while-typing = true
window-decoration = true
macos-option-as-alt = true
macos-titlebar-style = tabs
cursor-style = bar
cursor-style-blink = false
cursor-color = #f5e0dc
window-padding-x = 24
window-padding-y = 20
window-height = 45
window-width = 160
copy-on-select = clipboard
confirm-close-surface = false
keybind = super+left=unbind
keybind = super+right=unbind
command = /opt/homebrew/bin/fish -lc '/opt/homebrew/bin/tmux new-session'
